# -*- coding: utf-8 -*-
"""JobMatch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lTxPqOfHmUI4izCnEoVLEPGxQMJOHKH
"""

try:
    import jobspy
except ImportError:
    !pip install python-jobspy

#JOB SCRAPING APPLICATION

#1. Use AI to transform list of skills into list of job titles
#Add skill experience from user account

# 2. Use JobSpy to discover relevant job postings

from openai import OpenAI
import os
import ast

#Retrieve txt file of keywords
def txt_to_string(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

#Groq AI API key (will need a new one May 31st)
os.environ["GROQ_API_KEY"] = "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"

client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

#AI: Get list of job titles
def skills_to_job_titles(skills):
    prompt = f"""
    Given these skills
    Return a list of up to 5 relevant job titles.
    Only return a Python list of strings: {skills}
    """

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",  # fast + high quality
        messages=[
            {"role": "system", "content": "You are a helpful career assistant."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3
    )

    output = response.choices[0].message.content
    return output


#Get skills
skills = txt_to_string("extracted_skills.txt")

#Get titles from skills
titles = skills_to_job_titles(skills)

#Convert string list of job titles to Python list datatype
titles_list = ast.literal_eval(titles)

#-----------------Scrape Jobs-----------------------

import csv
from jobspy import scrape_jobs

# Construct the search term from the generated job titles
search_query = " OR ".join(titles_list)

jobs = scrape_jobs(
    site_name=["indeed", "linkedin", "zip_recruiter"], # "glassdoor", "bayt", "naukri", "bdjobs"
    search_term=search_query,
    google_search_term=f"{search_query} remote jobs since yesterday",
    location="Remote", #Remote also works
    results_wanted=20,
    hours_old=72,
    country_indeed='USA',

    # linkedin_fetch_description=True # gets more info such as description, direct job url (slower)
    # proxies=["208.195.175.46:65095", "208.195.175.45:65095", "localhost"],
)
print(f"Found {len(jobs)} jobs")
print(jobs.head())
jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False) # to_excel
